jobs:
  publish:
    docker:
      - image: circleci/circleci-cli
    steps:
      - checkout
      - compare-url/reconstruct
      - compare-url/use:
          custom-logic: |
                echo "COMMIT_RANGE $COMMIT_RANGE"
                echo "CIRCLE_COMPARE_URL $CIRCLE_COMPARE_URL"
          step-name: Publish modified orbs
orbs:
  compare-url: iynere/compare-url@x.y.z
version: 2.1
workflows:
  publish-orbs:
    jobs:
      - publish